---
title: "517_Abhinav"
author: "Abhinav"
date: "November 14, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(factoextra)
library(cluster) 
library(NbClust) 
library(fpc) 
library(dendroextras)
library(dendextend) 
library(mclust) 
library(dbscan) 
library(dplyr)
library(plyr)
```

```{r}
ds=read.csv("https://raw.githubusercontent.com/abhinav12347/stat-517/master/Final_517.csv")
dim(ds)


```

```{r}

is.na(ds$winner_seed)
ds$winner_seed[is.na(ds$winner_seed)]<-1
is.na(ds$winner_seed)
table(ds$winner_seed)
drop(ds$winner_seed)
names(ds)
str(ds)
```

```{r}
ds<-ds[,-c(1)]
names(ds)
ds<-ds[,-c(7)]
```


```{r}
ds<-ds[,-c(6)]
```

```{r}
ds<-ds[,-c(11)]

```

```{r}
ds<-ds[,-c(13)]

```

```{r}
ds<-ds[,-c(18)]

```

```{r}
ds<-ds[,-c(19)]

```

```{r}
names(ds)
```

```{r}
dim(ds)
```

```{r}
is.na(ds$draw_size)
```

```{r}
table(ds$draw_size)
is.na(ds$draw_size)
ds$draw_size[is.na(ds$draw)]<-32


```

```{r}
table(ds$tourney_level)
is.na(ds$tourney_level)
```


```{r}
table(ds$tourney_date)
is.na(ds$tourney_date)
```


```{r}
table(ds$winner_hand)
is.na(ds$winner_hand)
```

```{r}
ds$winner_hand[is.na(ds$winner_hand)]<-'R'

```

```{r}
table(ds$winner_ht)
is.na(ds$winner_ht)
```

```{r}
ds$winner_ht[is.na(ds$winner_ht)]<-185

```

```{r}
table(ds$winner_age)
is.na(ds$winner_age)
```

```{r}
ds$winner_age[is.na(ds$winner_age)]<-24

```

```{r}
ds$winner_rank_points[is.na(ds$winner_rank_points)]<-0.0

```

```{r}
ds$loser_hand[is.na(ds$loser_hand)]<-'R'

```

```{r}
ds$loser_ht[is.na(ds$loser_ht)]<-183

```

```{r}
ds$loser_age[is.na(ds$loser_age)]<-25

```

```{r}
ds$loser_rank_points[is.na(ds$loser_rank_points)]<-0.0

```

```{r}
ds$minutes[is.na(ds$minutes)]<-70.0

```

```{r}
ds$w_ace[is.na(ds$w_ace)]<-3.0

```

```{r}
ds$w_df[is.na(ds$w_df)]<-1.0

```

```{r}
ds$w_svpt[is.na(ds$w_svpt)]<-55.0

```

```{r}
ds$w_1stIn[is.na(ds$w_1stIn)]<-32.0

```

```{r}
ds$w_1stWon[is.na(ds$w_1stWon)]<-27.0

```

```{r}
ds$w_2ndWon[is.na(ds$w_2ndWon)]<-13.0

```

```{r}
ds$w_SvGms[is.na(ds$w_SvGms)]<-10.0

```

```{r}
ds$w_bpSaved[is.na(ds$w_bpSaved)]<-0.0

```

```{r}
ds$w_bpFaced[is.na(ds$w_bpFaced)]<-3.0

```

```{r}
ds$l_ace[is.na(ds$l_ace)]<-2.0

```

```{r}
ds$l_df[is.na(ds$l_df)]<-2.0

```

```{r}
ds$l_svpt[is.na(ds$l_svpt)]<-57.0

```

```{r}
ds$l_1stIn[is.na(ds$l_1stIn)]<-36.0

```

```{r}
ds$l_1stWon[is.na(ds$l_1stWon)]<-24.0

```

```{r}
ds$l_2ndWon[is.na(ds$l_2ndWon)]<-2.0

```

```{r}
ds$l_SvGms[is.na(ds$l_SvGms)]<-9.0

```

```{r}
ds$l_bpSaved[is.na(ds$l_bpSaved)]<-3.0

```

```{r}
ds$l_bpFaced[is.na(ds$l_bpFaced)]<-7.0

```

```{r}
ds_new = ds
```

```{r}
ds_new
```

```{r}
write.csv(ds_new,"Final_517_Updated_Abhinav.csv")

```

